export const EndPoints = {
  registerUser: `/post/register`,
  loginUser: `/post/login`,
  upsertHistory: '/post/upsert-history',
  requestPasswordReset: '/post/request-password-reset',
  verifyResetToken: '/post/verify-reset-token',
  resetPassword: '/post/reset-password',
  updateProfile: '/post/update-profile',
  verifyEmail: 'post/verify-email',
  requestDeleteAccount: 'post/request-delete-account',
  deleteAccount: 'post/delete-account',
  createSubscription: 'post/create-subscription',
  cancelSubscription: 'post/cancel-subscription',
  generateCoupon: 'post/generate-coupon',
  submitSupportQuery: 'post/submit-support-query',
  verifyCoupon: `/post/verify-coupon`,
  inviteUser: `/post/invite-user`,
  grantFullAccess: `/post/grant-full-access`,

  getUserDetail: `/get/user-detail`,
  getProducts: `/get/products`,
  getSellerInfo: `/get/seller-info`,
  searchProducts: `/get/search-product`,
  getProductOffer: `/get/product-offers`,
  graphImageWithProxy: `/get/graph-image`,
  findProductAsin: `/get/find-product-asins`,
  getGraphData: `/get/graph-data`,
  getSellerRevenue: `/get/calculate-seller-revenue`,
  getHistory: `/get/history`,
  aiChat: `/get/ai-chat`,
  getCoupons: `/get/coupons`,
  getInvitedUsers: `/get/invited-users`,

  deleteCoupon: `/delete/coupon`,
  deleteInvite: `/delete/invite`,
};
